### ISSUE TITLE
 是不是区分了大小写? 

### ISSUE THREAD

**Issue by nice2mu** [hankcs/hanlp-solr-plugin#18]
你好配置使用后,高亮区分了大小写.

是不是我要自己在加个
<filter class="solr.LowerCaseFilterFactory"/>

**Comment by hankcs** [comment]
也可以

enableNormalization	是否执行字符正规化（繁体->简体，全角->半角，大写->小写）	false

**Comment by nice2mu** [comment]
感谢!   是我没研究透!~
